/*
# Add media messaging support

## Summary
Extend the messages table to support photo, video, and audio messages in
addition to plain text. Media files are stored in a new private Supabase
Storage bucket (`chat-media`) and referenced by URL in the message row.

## 1. messages table changes
- Add `media_url` (text, nullable) — public/signed URL of the uploaded media
  file in the `chat-media` bucket. Null for plain text messages.
- Add `media_type` (text, nullable) — one of 'image', 'video', 'audio'. Null
  for plain text messages.
- Add `duration` (integer, nullable) — duration in seconds for audio/video
  clips (used to show a waveform/timer). Null for images and text.
- `text` is made nullable so a media-only message can have empty text. Existing
  text messages are unaffected.

## 2. Storage bucket
- Create a private storage bucket `chat-media` for uploading media files.
  Files are served via signed URLs generated by the authenticated client.

## 3. Storage policies
- SELECT (read/download): authenticated users can read objects in `chat-media/`
  so they can view media in conversations they have access to.
- INSERT (upload): authenticated users can upload to `chat-media/`.
- UPDATE / DELETE: authenticated users can update/delete objects they uploaded.
  Object ownership is determined by the path prefix `chat-media/<user_id>/...`,
  which the client uses when uploading (one folder per user).

## 4. Important notes
1. Media files are uploaded with a path of `chat-media/<owner_id>/<uuid>.<ext>`
   so each user's uploads live in their own folder. The UPDATE/DELETE policy
   checks that the path starts with the authenticated user's id.
2. The bucket is private; the frontend generates signed URLs to display media.
3. `text` is now nullable. Existing rows all have text, so no data is lost.
*/

-- 1. Add media columns to messages
ALTER TABLE messages
  ADD COLUMN IF NOT EXISTS media_url text,
  ADD COLUMN IF NOT EXISTS media_type text,
  ADD COLUMN IF NOT EXISTS duration integer;

ALTER TABLE messages ALTER COLUMN text DROP NOT NULL;

-- 2. Create the private chat-media storage bucket
INSERT INTO storage.buckets (id, name, public)
VALUES ('chat-media', 'chat-media', false)
ON CONFLICT (id) DO NOTHING;

-- 3. Storage policies
DROP POLICY IF EXISTS "authenticated_read_chat_media" ON storage.objects;
CREATE POLICY "authenticated_read_chat_media" ON storage.objects
  FOR SELECT TO authenticated
  USING (bucket_id = 'chat-media');

DROP POLICY IF EXISTS "authenticated_insert_chat_media" ON storage.objects;
CREATE POLICY "authenticated_insert_chat_media" ON storage.objects
  FOR INSERT TO authenticated
  WITH CHECK (bucket_id = 'chat-media');

DROP POLICY IF EXISTS "authenticated_update_chat_media" ON storage.objects;
CREATE POLICY "authenticated_update_chat_media" ON storage.objects
  FOR UPDATE TO authenticated
  USING (bucket_id = 'chat-media' AND owner = auth.uid())
  WITH CHECK (bucket_id = 'chat-media' AND owner = auth.uid());

DROP POLICY IF EXISTS "authenticated_delete_chat_media" ON storage.objects;
CREATE POLICY "authenticated_delete_chat_media" ON storage.objects
  FOR DELETE TO authenticated
  USING (bucket_id = 'chat-media' AND owner = auth.uid());
